# Generated by Django 4.1 on 2023-03-22 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0012_alter_review_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-createdAt"]},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name", "brand"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-createdAt"]},
        ),
        migrations.AlterModelOptions(
            name="shippingaddress",
            options={"ordering": ["order"]},
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="userreviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
